name: resonance
description: "Resonance - University Music Streaming & Student Platform"
publish_to: 'none'

version: 1.0.4+5

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.8.0+1
  just_audio: ^0.9.46
  audio_service: ^0.18.18
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.2
  google_sign_in: ^6.2.2
  connectivity_plus: ^6.1.4
  permission_handler: ^11.4.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
